language: ruby
require: sudo
sudo: true
rvm:
- 2.1
cache:
- bundler
install:
- bundle install --jobs=3 --retry=3
- bundle update
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
before_script:
- chmod +x ./build/*
script:
- "./build/build-demos.sh"
- bundle exec jekyll build
- bundle exec htmlproof ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: GX8Wx2KgMZkaOpwzNXEEihDNCvv3ShaNCkgHMxVdAfDf9gKkBuyb8tTigwtNyUkOLT15LrGQB2kjGuPmBoaY0PP910bjpCYMpZbSa7pCwZWu2GB2GSiL05OAF6qpH+Y5Eha1670MT0Q/n7yyKjXUJX7MNLno/n2sUjpOJkpzJi2zh+cL2aVWL9qb9UP6V1bw3Smvqv6ffi2LmsyDRwX83nXAPRclmj6RnqtrvN/jQ7a9ld/v7vxE6P95ej0z1JZpPIg43isDmGrn9SObd/6V6bxbboiqg2EOgx9YAbrtJ0f4ug5LKg6Kma1MVoeX58vAJoVDRFQBbtwL+DK5edktMCXYycmUPLjnDOeSuGFpyR9Hur0c+CqI3T5PIoR+pNnnKMI6rkL46+02Qksfilfe9Vserbew84tUTvP1F5oIMhy/DrnMe7vC1XI2fysOm82WcMkJJ0fblXe2E7kffual63RVWCGZ6jDzoEnguf6NCanuIwa0nyFRys6yNm6ZAfE9DxVkgnEUAb1EYECcLtzRh/3IFNHblAk2t9E8Hyqw8LfWcCHzVWiSTjMp7LggnwM35Cf22uQIH0flD7yD4dj4mvsjzHqRQWh1bZEqNTmGtAGf+M8Qw09o0PhvYFXrgCWoiR5lfc+wjg1jozAMB6qk/WTIFL6Z2OpZRwEAKCe5/C0=
branches:
  only:
  - master
after_success:
- if [[ "$TRAVIS_REPO_SLUG" == "SeiferTim/haxeflixel-mechanics" ]]; then bundle exec
  ruby ./build/serversync.rb; fi
