language: ruby
cache: bundler
rvm:
- 2.1
before_script: bundle update
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site
after_script: 
- serversync.rb
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer