language: ruby
require: sudo
sudo: true
rvm:
- 2.1
install:
- bundle install
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
- chmod +x ./build/*
- ./build/install-haxe.sh
before_script: 
- bundle update
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site
- ./build/build-demos.sh
after_script: 
- bundle exec ruby ./build/serversync.rb
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master