language: ruby
rvm:
- 2.1
before_script: 
- bundle update
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site
after_script: 
- chmod +x serversync.rb
- bundle exec ruby ./serversync.rb
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master