language: ruby
require: sudo
sudo: true
rvm:
- 2.1
cache:
- bundler
install:
- bundle install --jobs=3 --retry=3
- bundle update
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
before_script:
- chmod +x ./build/*
script:
- "./build/build-demos.sh"
- bundle exec jekyll build
- bundle exec htmlproof ./_site
- if [[ "${TRAVIS_REPO_SLUG}" = "SeiferTim/haxeflixel-mechanics" ]] && bundle exec ruby ./build/serversync.rb
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
