language: ruby
require: sudo
sudo: true
rvm:
- 2.1
cache:
- bundler
install:
- bundle install --jobs=3 --retry=3
- bundle update
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
before_script:
- chmod +x ./build/*
script:
- "./build/build-demos.sh"
- bundle exec jekyll build
- bundle exec htmlproof ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
after_success:
- if [[ "$TRAVIS_REPO_SLUG" == "SeiferTim/haxeflixel-mechanics" ]]; then bundle exec
  ruby ./build/serversync.rb; fi
