language: ruby
rvm:
- 2.1
install:
- bundle install
- chmod +x ./build/*
- ./build/install-haxe.sh
before_script: 
- bundle update
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site
- ./build/build_demos.sh
after_script: 
- bundle exec ruby ./build/serversync.rb
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master