name: CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: stable
        flixel-versions: dev
        target: html5
    - name: Build Site
      run: |
        gem install bundler
        bundle install --jobs=3 --retry=3
        bundle exec rake deploy
    - name: Highlighting
      run: |
        git clone --recursive https://github.com/Gama11/Highlighter
        cd Highlighter
        npm install
        node bin/highlighter.js ../_site
        cd ..
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.4.3
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: _site
        SINGLE_COMMIT: true
      if: github.ref == 'refs/heads/master'
