name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: krdlab/setup-haxe@v1
    - run: |
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib install flixel-addons
        haxelib install flixel-tools
    - run: |
        gem install bundler
        bundle install --jobs=3 --retry=3
        bundle exec rake deploy
